### ISSUE TITLE
Расширить информацию в отчете об остатке

### ISSUE THREAD

**Issue by vladimirgolovanov** [vladimirgolovanov/brihad-mridanga#7]
Сейчас есть только данные, что человек сообщил.

Расширить:

 - посчитать сколько должно быть не учитывая Лакшми (взял-вернул);
 - показать несостыковку взял-вернул-должно_остаться с отчетом;
 - вывести цифру, перевести разницу остатка введенного и остатку посчитанного в цифру;

**Comment by adbhutagaurangadas** [comment]
- инвертировать плюс и минус
- если сверхпожертвование, то писать 6570+450
- если минус, то он переходит на следующий период
